### PR TITLE
Allow different skey definitions by data standard version (and & this for grading periods v5.0)

### PR DESCRIPTION
**Pull request by rlittle08**
This branch updates `get_key()` macro to allow configuration of different natural keys across Ed-Fi versions. In particular, it implements this for grading periods, which had a change in unique key in Ed-Fi data standard v5.0.

- In the gen_skey dict, for `k_grading_period` only, I added new vars `diff_by_data_standard` and `ds_specific_col_lists`
- In the function, if `diff_by_data_standard`, then it evaluates SQL based on the keys within `ds_specific_col_lists` (e.g, if key is "< '5.0'", the SQL is "when data_model_version < '5.0'")
- Note, base tables will need data_model_version added (I added to the just the relevant tables for now)
- I also had to add a `case/when` in `stg_ef3__grading_periods`

Tested/QCd in SC

### CODE REVIEW

**Comment by rlittle08** [comment]
@ejoranlienea just ran a full test and confirmed this works for all models, even though `diff_by_data_standard` is only defined in the postive cases. This is bc Nones are treated as falsey by jinja, so the conditional code works as expected

**Comment by rlittle08** [comment]
@ejoranlienea any flags against me adding `ods_version` and `data_model_version` to every base table, which will allow for future applications of this config on any base model?

**Comment by ejoranlienea** [comment]
Yes, let's do that

**Comment by rlittle08** [comment]
@ejoranlienea I added to every base model and tested, this one is ready for final review

**Review by ejoranlienea — APPROVED** [review]

**Pull request merged**
